# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('value_name', models.CharField(help_text=b'Parameter value in the the geoserver api calls', max_length=100, unique=True)),
                ('is_string_usable', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=10, help_text=b'display order for user')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='ColorRamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('value_name', models.CharField(help_text=b'Parameter value in the the geoserver api calls', max_length=100)),
                ('sort_order', models.IntegerField(default=10, help_text=b'display order for user')),
                ('start_color', models.CharField(blank=True, help_text=b'hex color with "#", as in "#ffcc00"', max_length=30)),
                ('end_color', models.CharField(blank=True, help_text=b'hex color with "#", as in "#ffcc00"', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'display_name'),
            },
        ),
    ]
